apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./base
commonLabels:
  app.kubernetes.io/component: server
  app.kubernetes.io/managed-by: kleat
  app.kubernetes.io/part-of: spinnaker
  app.kubernetes.io/version: spinnaker-master-latest-validated
