apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: MINIO_ROOT_USER
          value: AKIAIOSFODNN7EXAMPLE
        - name: MINIO_ROOT_PASSWORD
          value: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        image: minio/minio:RELEASE.2021-12-09T06-19-41Z
        name: minio
        ports:
        - name: traffic-port
          containerPort: 9000
          protocol: TCP
        - name: console-port
          containerPort: 9001
          protocol: TCP
        args:
        - server
        - /data
        - "--console-address"
        - ":9001"
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
