apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
  - name: traffic-port
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console-port
    port: 9001
    protocol: TCP
    targetPort: 9001
  type: ClusterIP
