apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- config.yml
commonLabels:
  app.kubernetes.io/name: redis
  app.kubernetes.io/instance: redis
